/* eslint-disable no-console */
import { FullResult, Reporter, TestCase, TestResult } from '@playwright/test/reporter';
import * as fs from 'fs';
import * as path from 'path';
import { AppConfig } from '../config/AppConfig';
import { analyzeSummary, TestRunSummary } from './ai-test-analyzer';

class AIReporter implements Reporter {
  private result: TestRunSummary = {
    total: 0,
    passed: 0,
    failed: 0,
    broken: 0,
    skipped: 0,
    failures: [],
  };

  onTestEnd(test: TestCase, result: TestResult) {
    this.result.total++;
    switch (result.status) {
      case 'passed':
        this.result.passed++;
        break;
      case 'failed':
        this.result.failed++;
        this.addFailure(test, result);
        break;
      case 'timedOut':
        this.result.broken++;
        this.addFailure(test, result);
        break;
      case 'skipped':
        this.result.skipped++;
        break;
      case 'interrupted':
        this.result.broken++;
        break;
    }
  }

  private addFailure(test: TestCase, result: TestResult) {
    this.result.failures.push({
      name: test.title,
      file: test.location.file,
      error: result.error?.message || 'Unknown error',
      trace: result.error?.stack || '',
      analysisResult: result.annotations.find((a) => a.type === 'ai-analysis')?.description || '',
    });
  }

  async onEnd(result: FullResult) {
    if (result.status === 'passed') {
      console.log('\n✅ All tests passed. Skipping AI summary.');
      return;
    }

    console.log('\n🤖 Generating AI Test Summary...');
    const aiAnalysis = await analyzeSummary(this.result);

    const report = this.formatMarkdownReport(this.result, aiAnalysis);

    // Save to file
    const outputPath = path.join(process.cwd(), 'ai-analysis-report.md');
    fs.writeFileSync(outputPath, report);

    // Also log to console for visibility in CI
    console.log('\n=== AI TEST ANALYSIS ===\n');
    console.log(aiAnalysis);
    console.log('\n========================\n');
    console.log(`Report saved to: ${outputPath}`);

    // If running in GitHub Actions, add to Step Summary
    if (AppConfig.github.stepSummary) {
      fs.appendFileSync(AppConfig.github.stepSummary, report);
    }
  }

  private formatMarkdownReport(summary: TestRunSummary, aiAnalysis: string): string {
    const timestamp = new Date().toISOString();
    return `# 🤖 AI Test Analysis Report

> Generated: ${timestamp}

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Tests | ${summary.total} |
| ✅ Passed | ${summary.passed} |
| ❌ Failed | ${summary.failed} |
| 💔 Broken | ${summary.broken} |
| ⏭️ Skipped | ${summary.skipped} |

---

${aiAnalysis}

---
*This report was generated by AI.*
`;
  }
}

export default AIReporter;
