/* eslint-disable no-console */
import { FullResult, Reporter, TestCase, TestResult } from '@playwright/test/reporter';
import * as fs from 'fs';
import * as path from 'path';
import { AppConfig } from '../config/AppConfig';
import { analyzeSummary, FailureDetailSummary, TestRunSummary } from './ai-test-analyzer';

class AIReporter implements Reporter {
  private result: TestRunSummary = {
    total: 0,
    passed: 0,
    failed: 0,
    flaky: 0,
    broken: 0,
    skipped: 0,
    failures: [],
  };

  private testFailures: Map<TestCase, FailureDetailSummary> = new Map();

  onTestEnd(test: TestCase, result: TestResult) {
    if (
      result.status === 'failed' ||
      result.status === 'timedOut' ||
      result.status === 'interrupted'
    ) {
      this.handleFailure(test, result);
    } else if (result.status === 'passed') {
      this.result.passed++;
      this.result.total++;
    } else if (result.status === 'skipped') {
      this.result.skipped++;
      this.result.total++;
    }
  }

  private handleFailure(test: TestCase, result: TestResult) {
    // Add placeholder or update existing failure
    const failureSummary: FailureDetailSummary = {
      name: test.title,
      file: test.location.file,
      error: result.error?.message || 'Unknown error',
      trace: result.error?.stack || '',
      analysisResult: 'No AI analysis attached.',
    };

    // Prefer per-test AI analysis attached from the test layer (baseTest fixture)
    const aiAnalysisAttachment = result.attachments.find((a) => a.name === 'ai-analysis');

    if (aiAnalysisAttachment && aiAnalysisAttachment.path) {
      try {
        const analysis = fs.readFileSync(aiAnalysisAttachment.path, 'utf8');
        failureSummary.analysisResult = analysis;
      } catch (error) {
        console.error(
          `[AIReporter] Failed to read ai-analysis attachment for ${test.title}:`,
          error,
        );
        failureSummary.analysisResult = `Error reading ai-analysis attachment: ${
          error instanceof Error ? error.message : String(error)
        }`;
      }
    }

    this.testFailures.set(test, failureSummary);
  }

  async onEnd(result: FullResult) {
    if (result.status === 'passed' && this.testFailures.size === 0) {
      console.log('\n✅ All tests passed. Skipping AI summary.');
      return;
    }

    for (const test of this.testFailures.keys()) {
      const outcome = test.outcome();
      if (outcome === 'flaky') {
        this.result.flaky++;
        this.result.passed--;
      } else if (outcome === 'unexpected') {
        // Find if it was a timeout/interruption or a regular failure
        const lastResult = test.results[test.results.length - 1];
        if (
          lastResult &&
          (lastResult.status === 'timedOut' || lastResult.status === 'interrupted')
        ) {
          this.result.broken++;
          this.result.total++;
        } else {
          this.result.failed++;
          this.result.total++;
        }
      }
    }

    // Populate final failures list (only for those that actually failed in the end or are flaky)
    this.result.failures = Array.from(this.testFailures.values());

    console.log(this.result);

    console.log('\n🤖 Generating AI Test Summary...');
    const aiAnalysis = await analyzeSummary(this.result);

    const report = this.formatMarkdownReport(this.result, aiAnalysis);

    // Save to file
    const outputPath = path.join(process.cwd(), 'ai-analysis-report.md');
    fs.writeFileSync(outputPath, report);

    // Also log to console for visibility in CI
    console.log('\n=== AI TEST ANALYSIS ===\n');
    console.log(aiAnalysis);
    console.log('\n========================\n');
    console.log(`Report saved to: ${outputPath}`);

    // If running in GitHub Actions, add to Step Summary
    if (AppConfig.github.stepSummary) {
      fs.appendFileSync(AppConfig.github.stepSummary, report);
    }
  }

  private formatMarkdownReport(summary: TestRunSummary, aiAnalysis: string): string {
    const timestamp = new Date().toISOString();
    return `# 🤖 AI Test Analysis Report

> Generated: ${timestamp}

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Tests | ${summary.total} |
| ✅ Passed | ${summary.passed} |
| ❌ Failed | ${summary.failed} |
| 🔄 Flaky | ${summary.flaky} |
| 💔 Broken | ${summary.broken} |
| ⏭️ Skipped | ${summary.skipped} |

---

${aiAnalysis}

---
*This report was generated by AI.*
`;
  }
}

export default AIReporter;
